security:
    password_hashers:
        App\Entity\Users:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                target: /login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /

    access_control:
        # Pages accessibles sans connexion
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Pages nécessitant une authentification
        - { path: ^/felinementvotre, roles: ROLE_USER }
        - { path: ^/cats, roles: ROLE_USER }

        # Par défaut, tout le reste nécessite d'être connecté
        - { path: ^/, roles: ROLE_USER }
