# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\Users:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # GET /login sans auth
        login_get:
            pattern: ^/login$
            methods: [GET]
            security: false

        # GET /register sans auth
        register_get:
            pattern: ^/register$
            methods: [GET]
            security: false

        main:
            pattern: ^/
            lazy: true
            provider: app_user_provider

            # ← Remplace `custom_authenticator` par `custom_authenticators`
            custom_authenticators:
                - App\Security\AppCustomAuthenticator

            logout:
                path:   app_logout
                target: /login

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path:     /

    access_control:
        - { path: ^/felinementvotre, roles: ROLE_USER }
        - { path: ^/cats,            roles: ROLE_USER }
